### ISSUE TITLE
Upgrade to 1.0.0-beta.9 and UIRouterRx

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#166]
#After upgrading to 1.0.0-beta.9 I started to get the following error.
`**Property 'params$' does not exist on type 'UIRouterGlobals’.**`

along with 0
`/node_modules/@uirouter/rx/lib/ui-router-rx.d.ts (6,72): Cannot find module '@uirouter/core'`

I register the plugin as I was before (no code change form my side just uprooter upgrade from beta8 to beta9)
router.plugin(UIRouterRx);

**Comment by christopherthielen** [comment]
`@uirouter/rx` is included in `@uirouter/angular` and you no longer have to register the plugin yourself.  However, that doesn't explain the errors you're mentioning.  I had no trouble [upgrading the sample app](https://github.com/ui-router/sample-app-angular/commit/9d8e3e770b8aa1cbd211140de4f7da262b91b2e5).  How can I reproduce this error?  Can you check for duplicate copies of any of the `@uirouter/*` packages by running `npm ls`?

**Comment by mkoczorowski** [comment]
thanks @christopherthielen Will try again tonight and post the outcome

**Comment by mkoczorowski** [comment]
@christopherthielen do I still have to import ui-router-rx if I dont have to register the plugin ?
if I dont register the plugin I got this
```ERROR in src/app/app/navigation/navigation.service.ts(13,32): error TS2551: Property 'params$' does not exist on type 'UIRouterGlobals'. Did you mean 'params'?```

where
<img width="639" alt="navigation_service_ts_-_app2_0_-____sites_stockopedia_app2_0_" src="https://user-images.githubusercontent.com/8155896/32662910-02c17bb0-c624-11e7-893b-5e380b6d8cdd.png">

if I do include it
```import { UIRouterRx } from '@uirouter/rx';```

then
``` router.plugin(UIRouterRx); ```

like I had before, I'm getting
```
ERROR in node_modules/@uirouter/rx/lib/ui-router-rx.d.ts(6,72): error TS2307: Cannot find module '@uirouter/core'.
src/app/app/navigation/navigation.service.ts(13,32): error TS2551: Property 'params$' does not exist on type 'UIRouterGlobals'. Did you mean 'params'?
```

I have tried to remove_node_modules, clean cache and installig all again.. but still facing the issue

revering to beta.8 with both of those:
```
import { UIRouterRx } from '@uirouter/rx';
router.plugin(UIRouterRx); 
```

fixes the issue.

**Comment by mkoczorowski** [comment]
I dont see sample app using uirouterrx anywhere

**Comment by mkoczorowski** [comment]
I got it working ! 
I had to manually uninstall @uirouter/core, @uirouter/rx using npm uninstall -S, and install @uirouter/angular again…

Eh.. one of those days… 

@christopherthielen closing the issue. thanks for the support

**Comment by aleixsuau** [comment]
Hi,
Same problem here, I'm not able to access the UiRouterRx typings even after removing node_modeles and updating to "@uirouter/angular": "^6.0.2", "@uirouter/core": "^6.0.5",    "@uirouter/rx": "^0.6.5".

I was able to solve it by including the typings explicitly: 
/// <reference path="../node_modules/@uirouter/rx/lib/core.augment.d.ts" />
